(package "pyenv-mode"
         "0.1.0"
         "Integrate pyenv with python-mode")

(website-url "https://github.com/proofit404/pyenv-mode")
(keywords "convenience" "pyenv")

(package-file "pyenv-mode.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "25.1")
(depends-on "pythonic")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
